### ISSUE TITLE
Try this to fix script

### ISSUE THREAD

**Issue by Vega-KH** [AbyszOne/Abysz_lab#1]
Here is a rewrite of the code. I have not tested it:

Notice that I removed the "render" button completely. Generally, the correct way to run an extension is to use the normal "Generate" button inside AUTO1111. That is how I made it work now, just click the "Generate" button to run it.

```

import modules.scripts as scripts
import gradio as gr
import subprocess
import os
from PIL import Image
import sys
import cv2
import shutil
import time
            
from modules import images
from modules.processing import process_images, Processed
from modules.processing import Processed
from modules.shared import opts, cmd_opts, state


class Script(scripts.Script):

    # The title of the script.
    def title(self):
        return "Abysz Lab"

    # Determines when the script should be shown in the dropdown menu via the 
    
    def show(self, is_img2img):
        return is_img2img
    
                
    def ui(self, is_img2img):
        source_folder = gr.Textbox(label="Source images folder", value="J:\FULL")
        generated_folder = gr.Textbox(label="Generated images folder", value="d:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen")
        out_folder = gr.Textbox(label="Out", value="d:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen/out")
        slider1 = gr.Slider(minimum=1, maximum=30, value=5, step=1, label="Frame refresh frecuency")
        slider2 = gr.Slider(minimum=0, maximum=100, value=50, step=5, label="Refresh Strength")
        slider3 = gr.Slider(minimum=1, maximum=10, value=5, step=0.5, label="DFI Strength")
        slider4 = gr.Slider(minimum=0, maximum=10, value=4, step=1, label="DFI Deghost")
        slider5 = gr.Slider(minimum=1, maximum=99, value=25, step=2, label="Smooth")
        return [source_folder, generated_folder, out_folder, slider1, slider2, slider3, slider4, slider5]
    
    def run(self, p, src_folder, gen_folder, out_folder, slider1, slider2, slider3, slider4, slider5):
        # Definir las rutas de las carpetas
        maskD = os.path.join(os.getcwd(), 'extensions', 'Abysz-Deflicker', 'scripts', 'Run', 'MaskD')
        maskS = os.path.join(os.getcwd(), 'extensions', 'Abysz-Deflicker', 'scripts', 'Run', 'MaskS')
        output = out_folder #sets the output folder to the one the user selects
        source = src_folder #sets the output folder to the one the user selects
        gen = gen_folder #sets the output folder to the one the user selects
        
        os.makedirs(source, exist_ok=True)
        os.makedirs(maskS, exist_ok=True)
        os.makedirs(output, exist_ok=True)
        os.makedirs(maskD, exist_ok=True)
        os.makedirs(gen, exist_ok=True)
        
        # Copy the images from source_folder to run folder in JPEG quality 100
        for file in os.listdir(src_folder):
            if file.endswith(".jpg") or file.endswith(".jpeg") or file.endswith(".png"):
                img = Image.open(os.path.join(src_folder, file))
                img.save(os.path.join("./extensions/Abysz-Deflicker/scripts/Run/Source", file), "jpeg", quality=100)
        for file in os.listdir(gen_folder):
            if file.endswith(".jpg") or file.endswith(".jpeg") or file.endswith(".png"):
                img = Image.open(os.path.join(gen_folder, file))
                img.save(os.path.join("./extensions/Abysz-Deflicker/scripts/Run/Gen", file))
                
        # Carpeta donde se encuentran las imágenes de Gen
        #gen_folder = generated_folder_value
        
        # Carpeta donde se encuentran las imágenes de FULL
        full_folder = "./extensions/Abysz-Deflicker/scripts/Run/Source/"
        
        # Obtener la primera imagen en la carpeta Gen
        gen_images = os.listdir(gen_folder)
        gen_image_path = os.path.join(gen_folder, gen_images[0])
        gen_image = cv2.imread(gen_image_path)
        gen_height, gen_width = gen_image.shape[:2]
        gen_aspect_ratio = gen_width / gen_height
        
        # Recorrer todas las imágenes en la carpeta FULL
        for image_name in os.listdir(full_folder):
            image_path = os.path.join(full_folder, image_name)
            image = cv2.imread(image_path)
            height, width = image.shape[:2]
            aspect_ratio = width / height
        
            if aspect_ratio != gen_aspect_ratio:
                if aspect_ratio > gen_aspect_ratio:
                    # La imagen es más ancha que la imagen de Gen
                    crop_width = int(height * gen_aspect_ratio)
                    x = int((width - crop_width) / 2)
                    image = image[:, x:x+crop_width]
                else:
                    # La imagen es más alta que la imagen de Gen
                    crop_height = int(width / gen_aspect_ratio)
                    y = int((height - crop_height) / 2)
                    image = image[y:y+crop_height, :]
        
            # Redimensionar la imagen de FULL a la resolución de la imagen de Gen
            image = cv2.resize(image, (gen_width, gen_height))
        
            # Guardar la imagen redimensionada en la carpeta FULL
            cv2.imwrite(os.path.join(full_folder, image_name), image)
        

        source_dir = "./extensions/Abysz-Deflicker/scripts/Run/Source" # ruta de la carpeta "Source"
        
        # Obtener una lista de los nombres de archivo en la carpeta "Source"
        files = os.listdir(source_dir)
        
        # Renombrar cada archivo
        for i, file_name in enumerate(files):
            old_path = os.path.join(source_dir, file_name) # ruta actual del archivo
            new_file_name = f"{i+1:03d}" # nuevo nombre de archivo con formato %03d
            new_path = os.path.join(source_dir, new_file_name + os.path.splitext(file_name)[1]) # nueva ruta del archivo
            try:
                os.rename(old_path, new_path)
            except FileExistsError:
                print(f"El archivo {new_file_name} ya existe. Se omite su renombre.")
            
        gen_dir = "./extensions/Abysz-Deflicker/scripts/Run/Gen" # ruta de la carpeta "Source"
        
        # Obtener una lista de los nombres de archivo en la carpeta "Gen"
        files = os.listdir(gen_dir)
        
        # Renombrar cada archivo
        for i, file_name in enumerate(files):
            old_path = os.path.join(gen_dir, file_name) # ruta actual del archivo
            new_file_name = f"{i+1:03d}" # nuevo nombre de archivo con formato %03d
            new_path = os.path.join(gen_dir, new_file_name + os.path.splitext(file_name)[1]) # nueva ruta del archivo
            try:
                os.rename(old_path, new_path)
            except FileExistsError:
                print(f"El archivo {new_file_name} ya existe. Se omite su renombre.")

        # Obtener el primer archivo de la carpeta "Gen"
        gen_files = os.listdir("./extensions/Abysz-Deflicker/scripts/Run/Gen")
        if gen_files:
            first_gen_file = gen_files[0]

            # Copiar el archivo a la carpeta "Output" y reemplazar si ya existe
            output_file = "./extensions/Abysz-Deflicker/scripts/Run/Output/" + first_gen_file
            shutil.copyfile("./extensions/Abysz-Deflicker/scripts/Run/Gen/" + first_gen_file, output_file)
        
        #subprocess call
        
        # Definir la carpeta donde están los archivos
        carpeta = './extensions/Abysz-Deflicker/scripts/Run/Source/'
        
        # Crear la carpeta MaskD si no existe
        os.makedirs('./extensions/Abysz-Deflicker/scripts/Run/MaskD', exist_ok=True)
        
        # Inicializar contador
        contador = 1
        
        umbral_size = slider3
        # Iterar a través de los archivos de imagen en la carpeta Source
        for filename in sorted(os.listdir(carpeta)):
            # Cargar la imagen actual y la siguiente en escala de grises
            if contador > 1:
                siguiente = cv2.imread(os.path.join(carpeta, filename), cv2.IMREAD_GRAYSCALE)
                diff = cv2.absdiff(anterior, siguiente)
        
                # Aplicar un umbral y guardar la imagen resultante en la carpeta MaskD. Menos es más.
                umbral = umbral_size
                umbralizado = cv2.threshold(diff, umbral, 255, cv2.THRESH_BINARY_INV)[1] # Invertir los colores
                cv2.imwrite(os.path.join('./extensions/Abysz-Deflicker/scripts/Run/MaskD', f'{contador-1:03d}.png'), umbralizado)
        
            anterior = cv2.imread(os.path.join(carpeta, filename), cv2.IMREAD_GRAYSCALE)
            contador += 1
            
            #Actualmente, el tipo de umbralización es cv2.THRESH_BINARY_INV, que invierte los colores de la imagen umbralizada. 
            #Puedes cambiarlo a otro tipo de umbralización, 
            #como cv2.THRESH_BINARY, cv2.THRESH_TRUNC, cv2.THRESH_TOZERO o cv2.THRESH_TOZERO_INV.
        
        
        # Obtener la lista de los nombres de los archivos en la carpeta MaskD
        files = os.listdir("./extensions/Abysz-Deflicker/scripts/Run/MaskD")
        
        # Iterar sobre cada archivo
        for file in files:
            # Leer la imagen de la carpeta MaskD
            img = cv2.imread("./extensions/Abysz-Deflicker/scripts/Run/MaskD/" + file)
        
            # Invertir la imagen usando la función bitwise_not()
            img_inv = cv2.bitwise_not(img)
            
            kernel_size = slider4

            # Dilatar la imagen usando la función dilate()
            kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (kernel_size, kernel_size)) # Puedes cambiar el tamaño y la forma del kernel según tus preferencias
            img_dil = cv2.dilate(img_inv, kernel)
        
            # Volver a invertir la imagen usando la función bitwise_not()
            img_out = cv2.bitwise_not(img_dil)
        
            # Sobrescribir la imagen en la carpeta MaskD con el mismo nombre que el original
            cv2.imwrite("./extensions/Abysz-Deflicker/scripts/Run/MaskD/" + file, img_out)
            
        # Definir la carpeta donde están los archivos
        carpeta = "./extensions/Abysz-Deflicker/scripts/Run/MaskD"
        blur_kernel = slider5
        # Iterar a través de los archivos de imagen en la carpeta MaskD
        for imagen in os.listdir(carpeta):
            if imagen.endswith(".jpg") or imagen.endswith(".png") or imagen.endswith(".jpeg"):
                # Leer la imagen
                img = cv2.imread(os.path.join(carpeta, imagen))
                # Aplicar el filtro
                img = cv2.GaussianBlur(img, (blur_kernel,blur_kernel),0)
                # Guardar la imagen con el mismo nombre
                cv2.imwrite(os.path.join(carpeta, imagen), img)
        
        
        # INICIO DEL BATCH Obtener el nombre del archivo en MaskD sin ninguna extensión
        # Agregar una variable de contador de bucles
        loop_count = 0
        
        # Agregar un bucle while para ejecutar el código en bucle infinito
        while True:
        
            mask_files = sorted(os.listdir(maskD))
            if not mask_files:
                print(f"No se encontraron archivos en {maskD}")
                exit(1)
            
            mask = mask_files[0]
            maskname = os.path.splitext(mask)[0]
            
            # Obtener la ruta de la imagen en la subcarpeta de output que tiene el mismo nombre que la imagen en MaskD
            output_files = [f for f in os.listdir(output) if os.path.splitext(f)[0] == maskname]
            if not output_files:
                print(f"No se encontró en {output} una imagen con el mismo nombre que {maskname}.")
                exit(1)
            
            output_file = os.path.join(output, output_files[0])
            
            # Aplicar el comando magick composite con las opciones deseadas
            composite_command = f"magick composite -compose CopyOpacity {os.path.join(maskD, mask)} {output_file} {os.path.join(maskS, 'result.png')}"
            os.system(composite_command)
            
            # Obtener el nombre del archivo en output sin ninguna extensión
            name = os.path.splitext(os.path.basename(output_file))[0]
            
            # Renombrar el archivo result.png con el nombre del archivo en output y la extensión .png
            os.rename(os.path.join(maskS, 'result.png'), os.path.join(maskS, f"{name}.png"))
            
            #Guardar el directorio actual en una variable
            original_dir = os.getcwd()
            
            #Cambiar al directorio de la carpeta MaskS
            os.chdir(maskS)
            
            #Iterar a través de los archivos de imagen en la carpeta MaskS
            for imagen in sorted(os.listdir(".")):
                # Obtener el nombre de la imagen sin la extensión
                nombre, extension = os.path.splitext(imagen)
                # Obtener solo el número de la imagen
                numero = ''.join(filter(str.isdigit, nombre))
                # Definir el nombre de la siguiente imagen
                siguiente = f"{int(numero)+1:0{len(numero)}}{extension}"
                # Renombrar la imagen
                os.rename(imagen, siguiente)
            
            # Volver al directorio original
            os.chdir(original_dir)
            
            # Establecer un valor predeterminado para disolución
            dissolve = 100 if loop_count % slider1 != 0 else slider2
            #slider2 = gr.inputs.Slider(minimum=0, maximum=100, default=50, step=5, label="FPR Strength")
        
        
            # Obtener el nombre del archivo en MaskS sin la extensión
            maskS_files = [f for f in os.listdir(maskS) if os.path.isfile(os.path.join(maskS, f)) and f.endswith('.png')]
            if maskS_files:
                filename = os.path.splitext(maskS_files[0])[0]
            else:
                print(f"No se encontraron archivos de imagen en la carpeta '{maskS}'")
                filename = ''[0]
            
            # Salir del bucle si no hay más imágenes que procesar
            if not filename:
                break
            
            # Obtener la extensión del archivo en Gen con el mismo nombre
            gen_files = [f for f in os.listdir(gen) if os.path.isfile(os.path.join(gen, f)) and f.startswith(filename)]
            if gen_files:
                ext = os.path.splitext(gen_files[0])[1]
            else:
                print(f"No se encontró ningún archivo con el nombre '{filename}' en la carpeta '{gen}'")
                ext = ''
            
            input("Presione una tecla para continuar...")
            
            # Componer la imagen de MaskS y Gen con disolución (si está definido) y guardarla en la carpeta de salida
            os.system(f"magick composite {'-dissolve ' + str(dissolve) + '%' if dissolve is not None else ''} {maskS}/{filename}.png {gen}/{filename}{ext} {output}/{filename}{ext}")
            
            # Obtener el nombre del archivo más bajo en la carpeta MaskD
            maskd_files = [f for f in os.listdir(maskD) if os.path.isfile(os.path.join(maskD, f)) and f.startswith('')]
            if maskd_files:
                maskd_file = os.path.join(maskD, sorted(maskd_files)[0])
                os.remove(maskd_file)
            
            # Obtener el nombre del archivo más bajo en la carpeta MaskS
            masks_files = [f for f in os.listdir(maskS) if os.path.isfile(os.path.join(maskS, f)) and f.startswith('')]
            if masks_files:
                masks_file = os.path.join(maskS, sorted(masks_files)[0])
                os.remove(masks_file)
            
            input("Presione una tecla para continuar...")
            
            # Aumentar el contador de bucles
            loop_count += 1
```

**Comment by AbyszOne** [comment]
Thank you very much for your help!🙏 I thought about the generate button, but was afraid that being from img2img would conflict with my script that doesn't use img2img instances or the general interface. I don't know if it's the cause, but it gives me this error when I use the generate button. I'm going to investigate the changes you've made and try to learn from them to keep trying.

```
Error completing request
Arguments: ('task(o5wpdwj8xsxkpnq)', 0, '', '', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 12, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', True, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 3, 0, False, False, 0, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, None, '', 0.2, 0.1, 1, 1, False, True, True, False, False, False, False, 4, 1, 'None', 4, 0.09, True, 1, 0, 7, False, False, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, 'J:\\FULL', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen/out', 5, 50, 5, 4, 25, 'Render', 'J:\\FULL', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen/out', 5, 50, 5, 8, 9, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, True, None, None, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, True, True, 0, 0.1, 1, 'None', False, 0, 2, 512, 512, False, None, None, None, None, None, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2, '', '', False, '', 127, False, 30, 9999, 1, 10, 0.25, True, False, 'simple', '1', '', True, '', '', '', '', '', '', '', '', '', '', '', 'None', 0.3, 60) {}
Traceback (most recent call last):
  File "J:\A1111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "J:\A1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "J:\A1111\stable-diffusion-webui\modules\img2img.py", line 87, in img2img
    image = init_img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

Closing server running on port: 7894
Restarting UI...
[AddNet] Updating model hashes...
100%|████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 5333.30it/s]
add tab
Running on local URL:  http://0.0.0.0:7894

To create a public link, set `share=True` in `launch()`.
Startup time: 16.6s (list extensions: 4.1s, load scripts: 0.8s, create ui: 7.3s, gradio launch: 4.2s, scripts app_started_callback: 0.1s).
Error completing request
Arguments: ('task(j33w7gounnyi2f6)', 0, '', '', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 12, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', True, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 3, 0, False, False, 0, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, None, '', 0.2, 0.1, 1, 1, False, True, True, False, False, False, False, 4, 1, 'None', 4, 0.09, True, 1, 0, 7, False, False, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, 'J:\\FULL', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen/out', 5, 50, 5, 4, 25, 'Render', 'J:\\FULL', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen', 'd:/usuario/Documents/CONTROLNET/DEFLIKER/Maingradio/Gen/out', 5, 50, 5, 8, 7, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, True, None, None, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, True, True, 0, 0.1, 1, 'None', False, 0, 2, 512, 512, False, None, None, None, None, None, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2, '', '', False, '', 127, False, 30, 9999, 1, 10, 0.25, True, False, 'simple', '1', '', True, '', '', '', '', '', '', '', '', '', '', '', 'None', 0.3, 60) {}
Traceback (most recent call last):
  File "J:\A1111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "J:\A1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "J:\A1111\stable-diffusion-webui\modules\img2img.py", line 87, in img2img
    image = init_img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'
```

**Comment by LonicaMewinsky** [comment]
"Generate" button from the img2img tab requires an input (img2img, sketch, inpaint, etc). This function is probably better-suited as an additional tab rather than a script, especially since nothing is actually being "generated."

If you do go the Generate route, note that run() will require outputs, such as a list of return images, to populate the gallery. modules/ui.py has a ton of good examples and insight into how/why these interactions work.

**Comment by AbyszOne** [comment]
> "Generate" button from the img2img tab requires an input (img2img, sketch, inpaint, etc). This function is probably better-suited as an additional tab rather than a script, especially since nothing is actually being "generated."
> 
> If you do go the Generate route, note that run() will require outputs, such as a list of return images, to populate the gallery. modules/ui.py has a ton of good examples and insight into how/why these interactions work.

That is what I deduced, although I do not have the ability to carry it out. Luckily as a standalone gradio it works fine. I'll upload the corrected version shortly and start building from there.
